package lexer

type Tag int

const (
	// TOKENS
	TOKEN_FIM Tag = iota
	TOKEN_ERROR
	TOKEN_VARIAVEL
	TOKEN_NUMERO
	TOKEN_ATRIBUICAO
	TOKEN_VIRGULA
	TOKEN_IDENTACAO
	TOKEN_FIM_LINHA

	// ESTRUTURAS DE CONTROLE
	TOKEN_IF
	TOKEN_ELSE
	TOKEN_WHILE
	TOKEN_FOR

	// FUNÇÕES
	TOKEN_DEF
	TOKEN_PRINT
	TOKEN_READ
	TOKEN_INPUT

	// OPERADORES
	TOKEN_MAIS
	TOKEN_MENOS
	TOKEN_VEZES
	TOKEN_DIVIDIDO
	TOKEN_DIFERENTE
	TOKEN_IGUAL
	TOKEN_MAIOR_QUE
	TOKEN_MENOR_QUE
	TOKEN_MAIOR_IGUAL_QUE
	TOKEN_MENOR_IGUAL_QUE

	// DELIMITADORES
	TOKEN_ABRE_PARENTESES
	TOKEN_FECHA_PARENTESES
	TOKEN_DOIS_PONTOS
	TOKEN_ASPAS_DUPLAS
)

type Token struct {
	Tag    Tag
	Lexeme string
}

func (t Tag) String() string {
	switch t {
	case TOKEN_FIM:
		return "TOKEN_FIM"
	case TOKEN_ERROR:
		return "TOKEN_ERROR"
	case TOKEN_VARIAVEL:
		return "TOKEN_VARIAVEL"
	case TOKEN_NUMERO:
		return "TOKEN_NUMERO"
	case TOKEN_VIRGULA:
		return "TOKEN_VIRGULA"
	case TOKEN_IDENTACAO:
		return "TOKEN_IDENTACAO"
	case TOKEN_FIM_LINHA:
		return "TOKEN_FIM_LINHA"
	case TOKEN_IF:
		return "TOKEN_IF"
	case TOKEN_ELSE:
		return "TOKEN_ELSE"
	case TOKEN_WHILE:
		return "TOKEN_WHILE"
	case TOKEN_FOR:
		return "TOKEN_FOR"
	case TOKEN_DEF:
		return "TOKEN_DEF"
	case TOKEN_PRINT:
		return "TOKEN_PRINT"
	case TOKEN_READ:
		return "TOKEN_READ"
	case TOKEN_ATRIBUICAO:
		return "TOKEN_ATRIBUICAO"
	case TOKEN_INPUT:
		return "TOKEN_INPUT"
	case TOKEN_MAIS:
		return "TOKEN_MAIS"
	case TOKEN_MENOS:
		return "TOKEN_MENOS"
	case TOKEN_VEZES:
		return "TOKEN_VEZES"
	case TOKEN_DIVIDIDO:
		return "TOKEN_DIVIDIDO"
	case TOKEN_DIFERENTE:
		return "TOKEN_DIFERENTE"
	case TOKEN_IGUAL:
		return "TOKEN_IGUAL"
	case TOKEN_MAIOR_QUE:
		return "TOKEN_MAIOR_QUE"
	case TOKEN_MENOR_QUE:
		return "TOKEN_MENOR_QUE"
	case TOKEN_MAIOR_IGUAL_QUE:
		return "TOKEN_MAIOR_IGUAL_QUE"
	case TOKEN_MENOR_IGUAL_QUE:
		return "TOKEN_MENOR_IGUAL_QUE"
	case TOKEN_ABRE_PARENTESES:
		return "TOKEN_ABRE_PARENTESES"
	case TOKEN_FECHA_PARENTESES:
		return "TOKEN_FECHA_PARENTESES"
	case TOKEN_DOIS_PONTOS:
		return "TOKEN_DOIS_PONTOS"
	case TOKEN_ASPAS_DUPLAS:
		return "TOKEN_ASPAS_DUPLAS"
	default:
		return "TOKEN_DESCONHECIDO"
	}
}
